### PR TITLE
Reorganise and indent index.html and all CSS files using prettify

### PR DESCRIPTION
**Pull request by andela-araimi**
Fix [issue 5](https://github.com/TuhinKundu/CSE-2015-19-website/issues/5) and [issue 8](https://github.com/TuhinKundu/CSE-2015-19-website/issues/8)

### CODE REVIEW

**Comment by TuhinKundu** [comment]
Thanks for the PR. Can you also remove commented code?

**Comment by TuhinKundu** [comment]
Plus can I ask that have you done it manually or used a bot. Cuz it looks great!!! 👍

**Comment by andela-araimi** [comment]
Thanks for the compliment, I used a sublime package called `prettify` I will remove commented code as stated

**Comment by andela-araimi** [comment]
Please merge, the commented code has been removed

**Comment by andela-araimi** [comment]
I just indented all CSS files

**Comment by TuhinKundu** [comment]
Thanks a lot for your help and the PR.

**Comment by andela-araimi** [comment]
You are welcome

**Comment by TuhinKundu** [comment]
I am grateful to you for reorganizing the code for readability, but a credible amount of CSS isn't working which may be caused due to disconnection of index.html from some CSS files. I have made it an issue #12

**Pull request merged**
